menu:
  dashboard:
    name: dashboard
    url_path: /admin/dashboard
    icon: dashboard
    current: ['keppler_ga_dashboard/dashboard']
  seo:
    name: SEO
    current: ['admin/meta_tags', 'admin/google_adwords']
    icon: trending_up
    model: MetaTag
    submenu:
      - meta_tags:
          name: 'Title & Metas'
          url_path: /admin/meta_tags
          current: ['admin/meta_tags']
  script:
    name: Scripts
    url_path: /admin/scripts
    icon: settings_ethernet
    current: ['admin/scripts']
    model: Script
  destination:
    name: destinations
    url_path: /admin/destinations
    icon: flight_takeoff
    current: ['admin/destinations']
    model: Destination
  view:
    name: Landing Pages
    url_path: /admin/views
    icon: edit
    current: ['admin/views']
    model: View
  user:
    name: users
    url_path: /admin/users
    icon: account_circle
    current: ["admin/users"]
  setting:
    name: setting
    current: ['admin/settings']
    icon: settings
    model: Setting
    submenu:
      - basic_information:
          name: Basic information
          url_path: /admin/settings/basic_information
          current: ['basic_information']
      - smtp_setting:
          name: Email setting (SMTP)
          url_path: /admin/settings/email_setting
          current: ['email_setting']
      - google_analytics_setting:
          name: Google analytics
          url_path: /admin/settings/google_analytics_setting
          current: ['google_analytics_setting']
      - social_account:
          name: Social Accounts
          url_path: /admin/settings/social_accounts
          current: ['social_accounts']
